<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace QbaBit\CoreBundle\Command\Generator;

use QbaBit\CoreBundle\Command\Generator\Execute\BundleGenerator;
use Sensio\Bundle\GeneratorBundle\Manipulator\ConfigurationManipulator;
use Sensio\Bundle\GeneratorBundle\Model\Bundle;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Question\ConfirmationQuestion;
use Symfony\Component\HttpKernel\KernelInterface;
use Sensio\Bundle\GeneratorBundle\Manipulator\KernelManipulator;
use Sensio\Bundle\GeneratorBundle\Manipulator\RoutingManipulator;

/**
 * Generates bundles.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
class GenerateBundleCommand extends \Sensio\Bundle\GeneratorBundle\Command\GenerateBundleCommand
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    $this->setName('qbabit:generate:bundle');

    }

    protected function createGenerator()
    {
        return new BundleGenerator($this->getContainer()->get('filesystem'),$this->getContainer());
    }
}
