<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace QbaBit\CoreBundle\Command\Generator;

use QbaBit\CoreBundle\Command\Generator\Execute\ControllerGenerator;
use Sensio\Bundle\GeneratorBundle\Tests\Command\GenerateControllerCommandTest;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\ConfirmationQuestion;
use Symfony\Component\Console\Question\Question;
use Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper;

/**
 * Generates controllers.
 *
 * @author Wouter J <wouter@wouterj.nl>
 */
class GenerateControllerCommand extends \Sensio\Bundle\GeneratorBundle\Command\GenerateControllerCommand
{
    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('qbabit:generate:controller');
    }
   
    protected function createGenerator()
    {
        return new ControllerGenerator($this->getContainer()->get('filesystem'),$this->getContainer());
    }
}
