<?php

namespace QbaBit\LanguageBundle\Repository;

use QbaBit\CoreBundle\Repository\QbaBitBaseRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends QbaBitBaseRepository
{
    public function getListQuery($filter)
    {
        $query = $this->getBasicQuery(true);
        $name = "";
        if(array_key_exists("name",$filter))
            $name = $filter["name"];
        return $query->where('a.name LIKE :name')->setParameter('name','%'.$name.'%')->getQuery();

    }
    public function getLanguageByLocalization($localization)
    {
      /*  $query = $this->getBasicQuery(true);
        $query=$query->innerJoin('a.location','l')->where('l.code = :name')->setParameter('name',$localization);

        return  $query->getQuery()->getResult();*/
    }
}
