<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine.data.manager' shared service.

$this->services['liip_imagine.data.manager'] = $instance = new \Liip\ImagineBundle\Imagine\Data\DataManager(${($_ = isset($this->services['liip_imagine.binary.mime_type_guesser']) ? $this->services['liip_imagine.binary.mime_type_guesser'] : $this->load(__DIR__.'/getLiipImagine_Binary_MimeTypeGuesserService.php')) && false ?: '_'}, ${($_ = isset($this->services['liip_imagine.extension_guesser']) ? $this->services['liip_imagine.extension_guesser'] : $this->load(__DIR__.'/getLiipImagine_ExtensionGuesserService.php')) && false ?: '_'}, ${($_ = isset($this->services['liip_imagine.filter.configuration']) ? $this->services['liip_imagine.filter.configuration'] : $this->getLiipImagine_Filter_ConfigurationService()) && false ?: '_'}, 'default', NULL);

$instance->addLoader('default', ${($_ = isset($this->services['liip_imagine.binary.loader.default']) ? $this->services['liip_imagine.binary.loader.default'] : $this->load(__DIR__.'/getLiipImagine_Binary_Loader_DefaultService.php')) && false ?: '_'});

return $instance;
