<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'qba_bit_core.form.basic.general-datetime' shared service.

return $this->services['qba_bit_core.form.basic.general-datetime'] = new \QbaBit\CoreBundle\Form\Types\Basic\GeneralDateTimeType($this);
