<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'qba_bit.type.nauta.nauta.option' shared service.

return $this->services['qba_bit.type.nauta.nauta.option'] = new \QbaBit\NautaBundle\Form\Admin\NautaOptionsType($this);
