<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'qba_bit_nauta.render.menu' shared service.

return $this->services['qba_bit_nauta.render.menu'] = new \QbaBit\NautaBundle\MenuBuilder\AdminMenu($this);
