<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'qba_bit_security.listener.user.created' shared service.

return $this->services['qba_bit_security.listener.user.created'] = new \QbaBit\SecurityBundle\EventListener\UserRegisteredListener($this);
