<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'qba_bit_template.helper' shared service.

return $this->services['qba_bit_template.helper'] = new \QbaBit\TemplateBundle\Services\TemplateHelper($this);
