<?php

namespace QbaBit\CoreBundle\Controller\Modules;

use Doctrine\DBAL\Driver\Connection;
use Doctrine\ORM\EntityRepository;
use QbaBit\CoreBundle\Controller\Base\QbaBitCrudController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class QbaBitDynamicPagesController extends QbaBitCrudController
{
    /*protected function handleForm(Request $request, $object, Form $form)
     {
         $form->handleRequest($request);
         $this->doTest($request, $form);
         if ($form->isSubmitted() && $form->isValid()) {
             //------------
             $em = $this->get('doctrine.orm.default_entity_manager');
             if($object->getCode()==null)
                 $object->setCode($object->getName());
             $em->persist($object);
             $em->flush();
             $this->addFlash('success', $this->get('translator')->trans('qbabit.common.error.success'), true);
             return $this->redirect($this->generateUrl($this->getRedirectUrl()));
         }
         return false;
     }
   protected function additionalParams()
   {
       return  array_merge(parent::additionalParams(),array('edit_url'=>$this->getEditUrl(),'delete_url'=>$this->getDeleteUrl(),'redirect_url'=>$this->getRedirectUrl(),'new_url'=>$this->getNewUrl(),'prefix'=>$this->getGlobalTrans())); // TODO: Change the autogenerated stub
   }
   protected function getNewUrl()
   {
       return "";
   }
     protected function getDeleteUrl()
     {
         return "";
     }
     protected function getEditUrl()
     {
         return "";
     }
     protected function getEditRender()
     {
         return 'QbaBitCoreBundle:DynamicPages:edit.html.twig';
     }
     protected function getGlobalTrans()
     {
         return "";
     }



     protected function getIndexRender()
     {
         return 'QbaBitCoreBundle:DynamicPages:index.html.twig';
     }*/

}
