<?php
/**
 * Created by PhpStorm.
 * User: Administrador
 * Date: 26/08/2017
 * Time: 0:06
 */

namespace QbaBit\CoreBundle\Form\Editors\Images;



use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class  ImageFileMultipleEditor extends  ImageEditor
{

    public function useContainer()
    {
        return true;
    }

    public function hasAdditionalParams()
    {
        return true;
    }
    public function getUsesParams()
    {
        return array_merge(array('em'=>'Doctrine\ORM\EntityManager'),$this->uses);
    }
    public function getType()
    {
        return ImageFileMultipleType::class;
    }
    public function getDefaultTestValue()
    {
        $t = parent::getDefaultTestValue();
        $t['value'] = "[{\"name\":\"7.jpg\",\"type\":\"image/jpeg\",\"default\":true,\"reader\":{}},{\"name\":\"7Blade.jpg\",\"type\":\"image/jpeg\",\"default\":false,\"reader\":{}}]";
        $t['files']=  array('E:\Imagenes\Wallpapers\WIDE SCREEN\7.jpg', 'E:\Imagenes\Wallpapers\WIDE SCREEN\7Blade.jpg');
        return $t;
    }
    public function getPrincipalImage()
    {
        return "defaultImg"; // TODO: Change the autogenerated stub
    }
    public function getIndexHtml($value,$params)
    {
        $no = "asset('bundles/qbabitcore/css/common/images/no-img.png')";
        $ok = "(".str_replace("qbabit","",str_replace("bundle","",strtolower($params["bundle"]))).".uploads.".strtolower($params["table"]).".web~entity.defaultImg.image)";
        return '<img src="{{entity.defaultImg==null?'.$no.':'.$ok.' | imagine_filter(\'thumbnail\')  }}" width="32px" height="32px" >';
    }
}