<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'qba_bit_core.language.utils' shared service.

return $this->services['qba_bit_core.language.utils'] = new \QbaBit\CoreBundle\Services\LanguageUtils($this);
