<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'qba_bit_core.paginator.utils' shared service.

return $this->services['qba_bit_core.paginator.utils'] = new \QbaBit\CoreBundle\Services\PaginatorUtils($this, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['knp_paginator']) ? $this->services['knp_paginator'] : $this->load(__DIR__.'/getKnpPaginatorService.php')) && false ?: '_'});
