<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'qba_bit_security.manager.user' shared service.

return $this->services['qba_bit_security.manager.user'] = new \QbaBit\SecurityBundle\Services\UserManager($this);
