<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'qba_bit_security.forms.ip_type' shared service.

return $this->services['qba_bit_security.forms.ip_type'] = new \QbaBit\SecurityBundle\Form\Admin\SecurityIpType($this);
