QbaBit\SecurityBundle\Entity\SecuritySectionsRoles:
    type: entity
    table: security_sections_roles
    indexes:
        seccionid:
            columns:
                - section_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        section:
            targetEntity: SecuritySections
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                section_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        group:
            targetEntity: SecurityGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: role
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
