QbaBit\SecurityBundle\Entity\SecurityBackups:
    type: entity
    table: security_backups
    indexes:
        idusuario:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        comenten:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        filename:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: SecurityUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
