<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyjv8ra\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyjv8ra/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNyjv8ra.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNyjv8ra\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNyjv8ra\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nyjv8ra',
    'container.build_id' => '9f7b5a9b',
    'container.build_time' => 1548014997,
));
